#!/usr/bin/env python3
"""Scaffold Harbor-native private-repository benchmark intent.

``obench init`` is idempotent: existing files are never replaced.  The
historical OpenBench task scaffolder remains available only as explicit legacy
compatibility through ``--legacy-task`` (with ``--task`` as its old alias).
"""

from __future__ import annotations

import argparse
import os
import re
import sys

from . import add_task
from .config import CONFIG_DIRNAME, CONFIG_FILENAME


HARBOR_VERSION = "0.20.0"
HARBOR_COMMIT = "72bc40b1e58b47a9cc6e0f14c29aced3a9e53767"

OPENBENCH_TOML = """\
# OpenBench project configuration. Generated by `obench init`.
schema_version = 1
default_suite = ".openbench/suites/default.toml"
jobs_dir = ".openbench/jobs"
results_dir = ".openbench/results"
trajectories_dir = ".openbench/trajectories"
"""

GITIGNORE = """\
# Harbor job state and OpenBench result evidence are machine-local.
jobs/
results/

# ATIF trajectories can contain private source, prompts, and tool output.
trajectories/
"""

DEFAULT_SUITE_TOML = f"""\
schema_version = 1
id = "private-default"
title = "Private repository benchmark"

[harbor]
version = "{HARBOR_VERSION}"
commit = "{HARBOR_COMMIT}"

[[task_sets]]
id = "private"
kind = "local"
path = ".openbench/tasks"

[[arms]]
id = "codex-example"
harness = "codex"
profile = "local-codex"
model = "gpt-5.6-sol"

[run]
attempts = 1
concurrency = 1
max_retries = 0
timeout_seconds = 900

[evidence]
harbor_lock = true
verifier = true
trajectory = true
usage = true

[publication]
completeness = "complete"
"""

HARNESS_PROFILE_TOML = """\
# Declarative harness profile intent. Suite execution is not wired yet.
# Keep credentials and machine-local auth paths out of committed profiles.
schema_version = 1
id = "local-codex"
harness = "codex"
harbor_agent = "codex"
auth = "oauth"
cli_version = "0.144.5"
"""

EXAMPLE_INSTRUCTION = """\
# Write a greeting

Create `/app/greeting.txt` containing exactly `hello` followed by a newline.
"""

EXAMPLE_TASK_TOML = """\
schema_version = "1.4"
artifacts = [
    { source = "/app", destination = "workspace" },
]

[task]
name = "private/example-greeting"
version = "1.0.0"
description = "Create a greeting file."
authors = []
keywords = ["private", "example", "coding"]

[metadata]
origin = "obench-init"
difficulty = "easy"
category = "programming"
tags = ["private", "example"]

[verifier]
timeout_sec = 60.0

[agent]
timeout_sec = 900.0

[environment]
build_timeout_sec = 300.0
network_mode = "public"
os = "linux"
cpus = 1
memory_mb = 1024
storage_mb = 1024
gpus = 0
"""

EXAMPLE_DOCKERFILE = """\
FROM python:3.11-slim

WORKDIR /app
COPY app/ /app/
"""

EXAMPLE_APP_README = """\
# Example workspace

The agent starts here and creates `greeting.txt`.
"""

EXAMPLE_TEST = """\
#!/usr/bin/env bash
set -euo pipefail

reward_dir="${VERIFIER_LOGS_DIR:-/logs/verifier}"
mkdir -p "$reward_dir"
if [ -f greeting.txt ] && [ "$(cat greeting.txt)" = "hello" ]; then
  printf '%s\n' '{"reward": 1.0}' >"$reward_dir/reward.json"
else
  printf '%s\n' '{"reward": 0.0}' >"$reward_dir/reward.json"
fi
"""

EXAMPLE_SOLUTION = """\
#!/usr/bin/env bash
set -euo pipefail
printf 'hello\\n' >greeting.txt
"""


def _openbench_root(start: str | None = None) -> str:
    return os.path.join(os.path.abspath(start or os.getcwd()), CONFIG_DIRNAME)


def _write_new(
    path: str,
    contents: str,
    notes: list[str],
    *,
    executable: bool = False,
) -> bool:
    """Create one file without changing an existing path."""

    if os.path.exists(path):
        notes.append(f"skip (exists): {path}")
        return False
    parent = os.path.dirname(path)
    if parent:
        os.makedirs(parent, exist_ok=True)
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(contents)
    if executable:
        os.chmod(path, 0o755)
    notes.append(f"created: {path}")
    return True


def _ensure_dir(path: str, notes: list[str]) -> None:
    if os.path.isdir(path):
        notes.append(f"skip (exists): {path}/")
        return
    if os.path.exists(path):
        notes.append(f"skip (exists, not a directory): {path}")
        return
    os.makedirs(path)
    notes.append(f"created: {path}/")


def scaffold_harbor_example_task(tasks_dir: str, notes: list[str]) -> None:
    """Create one small Harbor schema 1.4 coding task without running it."""

    example = os.path.join(tasks_dir, "example-greeting")
    _ensure_dir(example, notes)
    _write_new(
        os.path.join(example, "instruction.md"),
        EXAMPLE_INSTRUCTION,
        notes,
    )
    _write_new(os.path.join(example, "task.toml"), EXAMPLE_TASK_TOML, notes)
    _write_new(
        os.path.join(example, "environment", "Dockerfile"),
        EXAMPLE_DOCKERFILE,
        notes,
    )
    _write_new(
        os.path.join(example, "environment", "app", "README.md"),
        EXAMPLE_APP_README,
        notes,
    )
    _write_new(
        os.path.join(example, "tests", "test.sh"),
        EXAMPLE_TEST,
        notes,
        executable=True,
    )
    _write_new(
        os.path.join(example, "solution", "solve.sh"),
        EXAMPLE_SOLUTION,
        notes,
        executable=True,
    )


def init_scaffold(start: str | None = None) -> list[str]:
    """Create the Harbor-native ``.openbench/`` project scaffold."""

    root = _openbench_root(start)
    notes: list[str] = []
    for directory in (
        root,
        os.path.join(root, "suites"),
        os.path.join(root, "tasks"),
        os.path.join(root, "profiles"),
        os.path.join(root, "jobs"),
        os.path.join(root, "results"),
        os.path.join(root, "trajectories"),
    ):
        _ensure_dir(directory, notes)
    _write_new(os.path.join(root, CONFIG_FILENAME), OPENBENCH_TOML, notes)
    _write_new(os.path.join(root, ".gitignore"), GITIGNORE, notes)
    _write_new(
        os.path.join(root, "suites", "default.toml"),
        DEFAULT_SUITE_TOML,
        notes,
    )
    _write_new(
        os.path.join(root, "profiles", "local-codex.toml"),
        HARNESS_PROFILE_TOML,
        notes,
    )
    scaffold_harbor_example_task(os.path.join(root, "tasks"), notes)
    return notes


def _valid_task_name(name: str) -> bool:
    return bool(re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9._-]*", name))


def init_task(
    name: str,
    from_dir: str | None = None,
    start: str | None = None,
    git_ref: str | None = None,
    git_subdir: str | None = None,
    git_repo: str = ".",
) -> str:
    """Create a legacy OpenBench checker task outside Harbor task sets."""

    if not _valid_task_name(name):
        raise ValueError(
            f"invalid task name {name!r}; use letters, digits, ., _, - "
            "(must start with alphanumeric)"
        )
    root = _openbench_root(start)
    legacy_tasks_dir = os.path.join(root, "legacy-tasks")
    os.makedirs(legacy_tasks_dir, exist_ok=True)
    init_scaffold(start)
    return add_task.scaffold(
        os.path.join(legacy_tasks_dir, name),
        from_dir=from_dir,
        git_ref=git_ref,
        git_subdir=git_subdir,
        git_repo=git_repo,
    )


def main(argv=None):
    parser = argparse.ArgumentParser(
        description="Scaffold Harbor-native .openbench/ benchmark intent.",
    )
    parser.add_argument(
        "--legacy-task",
        "--task",
        dest="task",
        metavar="NAME",
        help=(
            "LEGACY compatibility: create .openbench/legacy-tasks/NAME "
            "(--task is the deprecated spelling)"
        ),
    )
    parser.add_argument(
        "--from",
        dest="from_dir",
        metavar="DIR",
        help="with --legacy-task: copy DIR into the old workspace/ format",
    )
    parser.add_argument(
        "--git-ref",
        metavar="REF",
        help="with --legacy-task: write legacy workspace.toml pinned to REF",
    )
    parser.add_argument(
        "--git-subdir",
        metavar="PATH",
        help="with --git-ref: stage only this legacy repository subtree",
    )
    parser.add_argument(
        "--git-repo",
        default=".",
        metavar="REPO",
        help="with --git-ref: legacy local path or URL (default: .)",
    )
    args = parser.parse_args(argv)

    if args.from_dir and not args.task:
        parser.error("--from requires --legacy-task (or deprecated --task)")
    if args.git_ref and not args.task:
        parser.error("--git-ref requires --legacy-task (or deprecated --task)")
    if args.git_subdir and not args.git_ref:
        parser.error("--git-subdir requires --git-ref")
    if args.from_dir and args.git_ref:
        parser.error("use either --from or --git-ref, not both")

    if args.task:
        try:
            task_path = init_task(
                args.task,
                from_dir=args.from_dir,
                git_ref=args.git_ref,
                git_subdir=args.git_subdir,
                git_repo=args.git_repo,
            )
        except (FileExistsError, NotADirectoryError, ValueError, OSError) as exc:
            print(f"obench init: {exc}", file=sys.stderr)
            return 1
        print(f"Created LEGACY OpenBench task scaffold: {task_path}")
        print(
            "This task is not part of the Harbor-native default suite.\n"
            "Next command: obench validate --tasks-dir .openbench/legacy-tasks\n"
            "Migration: author a Harbor 1.4 task under .openbench/tasks/."
        )
        return 0

    notes = init_scaffold()
    print("Harbor-native OpenBench scaffold (.openbench/):")
    for note in notes:
        print(f"  {note}")
    print()
    print(
        "Next command (parse and validate suite intent):\n"
        "  python3 -c 'from obench.suite import load_suite; "
        "load_suite(\".openbench/suites/default.toml\")'\n"
        "Then edit the suite, task, and profile for this repository.\n"
        "Suite execution is intentionally not wired to `obench run` yet.\n"
        "See docs/private-evals.md and docs/harbor-suites.md."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
