#!/usr/bin/env python3
"""Scaffold Harbor-native private-repository benchmark intent.

``obench init`` is idempotent: authored files are never replaced, and the local
artifact ignore file is only augmented with missing safety rules.  The
historical OpenBench task scaffolder remains available only as explicit legacy
compatibility through ``--legacy-task`` (with ``--task`` as its old alias).
"""

from __future__ import annotations

import argparse
import os
from pathlib import Path
import re
import stat
import sys

from . import add_task
from .config import CONFIG_DIRNAME, CONFIG_FILENAME


HARBOR_VERSION = "0.20.0"
HARBOR_COMMIT = "72bc40b1e58b47a9cc6e0f14c29aced3a9e53767"

OPENBENCH_TOML = """\
# OpenBench project configuration. Generated by `obench init`.
schema_version = 1
default_suite = ".openbench/suites/default.toml"
jobs_dir = ".openbench/jobs"
results_dir = ".openbench/results"
trajectories_dir = ".openbench/trajectories"
"""

GITIGNORE = """\
# Harbor job state and OpenBench result evidence are machine-local.
jobs/
results/

# ATIF trajectories can contain private source, prompts, and tool output.
trajectories/
"""

DEFAULT_SUITE_TOML = f"""\
schema_version = 1
id = "private-default"
title = "Private repository benchmark"

[harbor]
version = "{HARBOR_VERSION}"
commit = "{HARBOR_COMMIT}"

[[task_sets]]
id = "private"
kind = "local"
path = ".openbench/tasks"

[[arms]]
id = "codex-example"
harness = "codex"
profile = "local-codex"
model = "gpt-5.6-sol"

[run]
attempts = 1
concurrency = 1
max_retries = 0
timeout_seconds = 900

[evidence]
harbor_lock = true
verifier = true
trajectory = true
usage = true

[publication]
scope = "local_only"
completeness = "complete"
"""

HARNESS_PROFILE_TOML = """\
# Declarative stock harness profile intent.
# Keep credentials and machine-local auth paths out of committed profiles.
schema_version = 1
id = "local-codex"
kind = "stock"
harness = "codex"
"""

EXAMPLE_INSTRUCTION = """\
# Write a greeting

Create `/app/greeting.txt` containing exactly `hello` followed by a newline.
"""

EXAMPLE_TASK_TOML = """\
schema_version = "1.4"
artifacts = [
    { source = "/app", destination = "workspace" },
]

[task]
name = "private/example-greeting"
version = "1.0.0"
description = "Create a greeting file."
authors = []
keywords = ["private", "example", "coding"]

[metadata]
origin = "obench-init"
difficulty = "easy"
category = "programming"
tags = ["private", "example"]

[verifier]
timeout_sec = 60.0

[agent]
timeout_sec = 900.0

[environment]
build_timeout_sec = 300.0
network_mode = "public"
os = "linux"
cpus = 1
memory_mb = 1024
storage_mb = 1024
gpus = 0
"""

EXAMPLE_DOCKERFILE = """\
FROM python:3.11-slim

WORKDIR /app
COPY app/ /app/
"""

EXAMPLE_APP_README = """\
# Example workspace

The agent starts here and creates `greeting.txt`.
"""

EXAMPLE_TEST = """\
#!/usr/bin/env bash
set -euo pipefail

reward_dir="${VERIFIER_LOGS_DIR:-/logs/verifier}"
mkdir -p "$reward_dir"
if [ -f greeting.txt ] && python3 -c \
  'from pathlib import Path; raise SystemExit(Path("greeting.txt").read_bytes() != b"hello\\n")'
then
  printf '%s\n' '{"reward": 1.0}' >"$reward_dir/reward.json"
else
  printf '%s\n' '{"reward": 0.0}' >"$reward_dir/reward.json"
fi
"""

EXAMPLE_SOLUTION = """\
#!/usr/bin/env bash
set -euo pipefail
printf 'hello\\n' >greeting.txt
"""


def _openbench_root(start: str | None = None) -> str:
    return os.path.join(os.path.abspath(start or os.getcwd()), CONFIG_DIRNAME)


def _scaffold_location(path: str) -> tuple[str, tuple[str, ...]]:
    absolute = Path(os.path.abspath(path))
    indices = [
        index
        for index, part in enumerate(absolute.parts)
        if part == CONFIG_DIRNAME
    ]
    if not indices:
        raise OSError(f"scaffold path is outside {CONFIG_DIRNAME}: {path}")
    root_index = indices[-1]
    root = Path(*absolute.parts[:root_index + 1])
    return os.fspath(root), tuple(absolute.parts[root_index + 1:])


def _directory_flags() -> int:
    return (
        os.O_RDONLY
        | getattr(os, "O_DIRECTORY", 0)
        | getattr(os, "O_NOFOLLOW", 0)
    )


def _open_scaffold_directory(path: str, *, create: bool) -> int:
    """Open a scaffold directory without following links below ``.openbench``."""

    root, parts = _scaffold_location(path)
    if os.path.lexists(root):
        if os.path.islink(root):
            raise OSError(f"refusing symlinked scaffold path: {root}")
        if not os.path.isdir(root):
            raise NotADirectoryError(f"scaffold root is not a directory: {root}")
    elif create:
        os.mkdir(root)
    else:
        raise FileNotFoundError(root)

    try:
        directory_fd = os.open(root, _directory_flags())
    except OSError as exc:
        raise OSError(
            f"refusing symlinked or invalid scaffold path: {root}"
        ) from exc

    current = root
    try:
        for part in parts:
            current = os.path.join(current, part)
            try:
                child_fd = os.open(
                    part,
                    _directory_flags(),
                    dir_fd=directory_fd,
                )
            except FileNotFoundError:
                if not create:
                    raise
                try:
                    os.mkdir(part, dir_fd=directory_fd)
                except FileExistsError:
                    pass
                try:
                    child_fd = os.open(
                        part,
                        _directory_flags(),
                        dir_fd=directory_fd,
                    )
                except OSError as exc:
                    raise OSError(
                        f"refusing symlinked or invalid scaffold path: {current}"
                    ) from exc
            except OSError as exc:
                raise OSError(
                    f"refusing symlinked or invalid scaffold path: {current}"
                ) from exc
            os.close(directory_fd)
            directory_fd = child_fd
        return directory_fd
    except BaseException:
        os.close(directory_fd)
        raise


def _write_new(
    path: str,
    contents: str,
    notes: list[str],
    *,
    executable: bool = False,
) -> bool:
    """Create one file without changing an existing path."""

    parent = os.path.dirname(path)
    parent_fd = _open_scaffold_directory(parent, create=True)
    name = os.path.basename(path)
    try:
        try:
            existing = os.stat(name, dir_fd=parent_fd, follow_symlinks=False)
        except FileNotFoundError:
            existing = None
        if existing is not None:
            if stat.S_ISLNK(existing.st_mode):
                raise OSError(f"refusing symlinked scaffold path: {path}")
            notes.append(f"skip (exists): {path}")
            return False

        flags = os.O_WRONLY | os.O_CREAT | os.O_EXCL | getattr(
            os, "O_NOFOLLOW", 0
        )
        try:
            file_fd = os.open(name, flags, 0o666, dir_fd=parent_fd)
        except FileExistsError:
            existing = os.stat(name, dir_fd=parent_fd, follow_symlinks=False)
            if stat.S_ISLNK(existing.st_mode):
                raise OSError(f"refusing symlinked scaffold path: {path}")
            notes.append(f"skip (exists): {path}")
            return False
        with os.fdopen(file_fd, "w", encoding="utf-8") as handle:
            handle.write(contents)
            handle.flush()
            os.fsync(handle.fileno())
            if executable:
                os.fchmod(handle.fileno(), 0o755)
    finally:
        os.close(parent_fd)
    notes.append(f"created: {path}")
    return True


def _ensure_dir(path: str, notes: list[str]) -> None:
    existed = os.path.lexists(path)
    directory_fd = _open_scaffold_directory(path, create=True)
    os.close(directory_fd)
    notes.append(
        f"skip (exists): {path}/" if existed else f"created: {path}/"
    )


def _ensure_gitignore(path: str, notes: list[str]) -> None:
    parent_fd = _open_scaffold_directory(os.path.dirname(path), create=True)
    name = os.path.basename(path)
    try:
        try:
            existing = os.stat(name, dir_fd=parent_fd, follow_symlinks=False)
        except FileNotFoundError:
            existing = None
        if existing is None:
            os.close(parent_fd)
            parent_fd = -1
            _write_new(path, GITIGNORE, notes)
            return
        if stat.S_ISLNK(existing.st_mode):
            raise OSError(f"refusing symlinked scaffold path: {path}")
        if not stat.S_ISREG(existing.st_mode):
            notes.append(f"skip (exists, not a regular file): {path}")
            return

        flags = os.O_RDWR | getattr(os, "O_NOFOLLOW", 0)
        file_fd = os.open(name, flags, dir_fd=parent_fd)
        with os.fdopen(file_fd, "r+", encoding="utf-8") as handle:
            contents = handle.read()
            existing_lines = set(contents.splitlines())
            missing = [
                entry for entry in ("jobs/", "results/", "trajectories/")
                if entry not in existing_lines
            ]
            if not missing:
                notes.append(f"skip (exists): {path}")
                return
            if contents and not contents.endswith("\n"):
                handle.write("\n")
            handle.write(
                "\n# Harbor/OpenBench private runtime artifacts.\n"
                + "".join(f"{entry}\n" for entry in missing)
            )
            handle.flush()
            os.fsync(handle.fileno())
        notes.append(f"updated: {path} (added {', '.join(missing)})")
    finally:
        if parent_fd >= 0:
            os.close(parent_fd)


def _reject_existing_file_symlink(path: str) -> None:
    try:
        parent_fd = _open_scaffold_directory(
            os.path.dirname(path),
            create=False,
        )
    except FileNotFoundError:
        return
    try:
        try:
            existing = os.stat(
                os.path.basename(path),
                dir_fd=parent_fd,
                follow_symlinks=False,
            )
        except FileNotFoundError:
            return
        if stat.S_ISLNK(existing.st_mode):
            raise OSError(f"refusing symlinked scaffold path: {path}")
    finally:
        os.close(parent_fd)


def _requires_harbor_task_isolation(tasks_dir: str) -> bool:
    if os.path.exists(tasks_dir) and not os.path.isdir(tasks_dir):
        return True
    if not os.path.isdir(tasks_dir):
        return False
    for name in os.listdir(tasks_dir):
        child = os.path.join(tasks_dir, name)
        if os.path.islink(child):
            return True
        if not os.path.isdir(child):
            continue
        complete_harbor = (
            os.path.isfile(os.path.join(child, "task.toml"))
            and os.path.isfile(os.path.join(child, "instruction.md"))
        )
        legacy_markers = (
            os.path.exists(os.path.join(child, "checker.sh"))
            or os.path.exists(os.path.join(child, "workspace"))
            or os.path.exists(os.path.join(child, "workspace.toml"))
            or (
                os.path.isfile(os.path.join(child, "instruction.md"))
                and not os.path.isfile(os.path.join(child, "task.toml"))
            )
        )
        if legacy_markers:
            return True
        if name == "example-greeting" and not complete_harbor:
            return True
    return False


def _select_harbor_tasks_dir(root: str, notes: list[str]) -> str:
    default = os.path.join(root, "tasks")
    if os.path.islink(default):
        raise OSError(f"refusing symlinked scaffold path: {default}")
    if not _requires_harbor_task_isolation(default):
        return default
    isolated = os.path.join(root, "harbor-tasks")
    notes.append(
        f"legacy/colliding task tree preserved: {default}/; "
        f"using {isolated}/"
    )
    return isolated


def _suite_toml(root: str, tasks_dir: str) -> str:
    project_root = os.path.dirname(root)
    relative = os.path.relpath(tasks_dir, project_root).replace(os.sep, "/")
    return DEFAULT_SUITE_TOML.replace(
        'path = ".openbench/tasks"',
        f'path = "{relative}"',
        1,
    )


def scaffold_harbor_example_task(tasks_dir: str, notes: list[str]) -> None:
    """Create one small Harbor schema 1.4 coding task without running it."""

    example = os.path.join(tasks_dir, "example-greeting")
    if os.path.lexists(example):
        directory_fd = _open_scaffold_directory(example, create=False)
        os.close(directory_fd)
        for directory in (
            os.path.join(example, "environment"),
            os.path.join(example, "environment", "app"),
            os.path.join(example, "tests"),
            os.path.join(example, "solution"),
        ):
            if os.path.lexists(directory):
                directory_fd = _open_scaffold_directory(
                    directory,
                    create=False,
                )
                os.close(directory_fd)
        for file_path in (
            os.path.join(example, "instruction.md"),
            os.path.join(example, "task.toml"),
            os.path.join(example, "environment", "Dockerfile"),
            os.path.join(example, "environment", "app", "README.md"),
            os.path.join(example, "tests", "test.sh"),
            os.path.join(example, "solution", "solve.sh"),
        ):
            _reject_existing_file_symlink(file_path)
        notes.append(f"skip (exists): {example}/")
        return
    _ensure_dir(example, notes)
    _write_new(
        os.path.join(example, "instruction.md"),
        EXAMPLE_INSTRUCTION,
        notes,
    )
    _write_new(os.path.join(example, "task.toml"), EXAMPLE_TASK_TOML, notes)
    _write_new(
        os.path.join(example, "environment", "Dockerfile"),
        EXAMPLE_DOCKERFILE,
        notes,
    )
    _write_new(
        os.path.join(example, "environment", "app", "README.md"),
        EXAMPLE_APP_README,
        notes,
    )
    _write_new(
        os.path.join(example, "tests", "test.sh"),
        EXAMPLE_TEST,
        notes,
        executable=True,
    )
    _write_new(
        os.path.join(example, "solution", "solve.sh"),
        EXAMPLE_SOLUTION,
        notes,
        executable=True,
    )


def init_scaffold(start: str | None = None) -> list[str]:
    """Create the Harbor-native ``.openbench/`` project scaffold."""

    root = _openbench_root(start)
    notes: list[str] = []
    for directory in (
        root,
        os.path.join(root, "suites"),
        os.path.join(root, "profiles"),
        os.path.join(root, "jobs"),
        os.path.join(root, "results"),
        os.path.join(root, "trajectories"),
    ):
        _ensure_dir(directory, notes)
    tasks_dir = _select_harbor_tasks_dir(root, notes)
    _ensure_dir(tasks_dir, notes)
    _write_new(os.path.join(root, CONFIG_FILENAME), OPENBENCH_TOML, notes)
    _ensure_gitignore(os.path.join(root, ".gitignore"), notes)
    _write_new(
        os.path.join(root, "suites", "default.toml"),
        _suite_toml(root, tasks_dir),
        notes,
    )
    _write_new(
        os.path.join(root, "profiles", "local-codex.toml"),
        HARNESS_PROFILE_TOML,
        notes,
    )
    scaffold_harbor_example_task(tasks_dir, notes)
    return notes


def _valid_task_name(name: str) -> bool:
    return bool(re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9._-]*", name))


def init_task(
    name: str,
    from_dir: str | None = None,
    start: str | None = None,
    git_ref: str | None = None,
    git_subdir: str | None = None,
    git_repo: str = ".",
) -> str:
    """Create a legacy OpenBench checker task outside Harbor task sets."""

    if not _valid_task_name(name):
        raise ValueError(
            f"invalid task name {name!r}; use letters, digits, ., _, - "
            "(must start with alphanumeric)"
        )
    root = _openbench_root(start)
    legacy_tasks_dir = os.path.join(root, "legacy-tasks")
    init_scaffold(start)
    _ensure_dir(legacy_tasks_dir, [])
    return add_task.scaffold(
        os.path.join(legacy_tasks_dir, name),
        from_dir=from_dir,
        git_ref=git_ref,
        git_subdir=git_subdir,
        git_repo=git_repo,
    )


def main(argv=None):
    parser = argparse.ArgumentParser(
        description="Scaffold Harbor-native .openbench/ benchmark intent.",
    )
    parser.add_argument(
        "--legacy-task",
        "--task",
        dest="task",
        metavar="NAME",
        help=(
            "LEGACY compatibility: create .openbench/legacy-tasks/NAME "
            "(--task is the deprecated spelling)"
        ),
    )
    parser.add_argument(
        "--from",
        dest="from_dir",
        metavar="DIR",
        help="with --legacy-task: copy DIR into the old workspace/ format",
    )
    parser.add_argument(
        "--git-ref",
        metavar="REF",
        help="with --legacy-task: write legacy workspace.toml pinned to REF",
    )
    parser.add_argument(
        "--git-subdir",
        metavar="PATH",
        help="with --git-ref: stage only this legacy repository subtree",
    )
    parser.add_argument(
        "--git-repo",
        default=".",
        metavar="REPO",
        help="with --git-ref: legacy local path or URL (default: .)",
    )
    args = parser.parse_args(argv)

    if args.from_dir and not args.task:
        parser.error("--from requires --legacy-task (or deprecated --task)")
    if args.git_ref and not args.task:
        parser.error("--git-ref requires --legacy-task (or deprecated --task)")
    if args.git_subdir and not args.git_ref:
        parser.error("--git-subdir requires --git-ref")
    if args.from_dir and args.git_ref:
        parser.error("use either --from or --git-ref, not both")

    if args.task:
        try:
            task_path = init_task(
                args.task,
                from_dir=args.from_dir,
                git_ref=args.git_ref,
                git_subdir=args.git_subdir,
                git_repo=args.git_repo,
            )
        except (FileExistsError, NotADirectoryError, ValueError, OSError) as exc:
            print(f"obench init: {exc}", file=sys.stderr)
            return 1
        print(f"Created LEGACY OpenBench task scaffold: {task_path}")
        print(
            "This task is not part of the Harbor-native default suite.\n"
            "Next command: obench validate --tasks-dir .openbench/legacy-tasks\n"
            "Migration: author a Harbor 1.4 task under .openbench/tasks/."
        )
        return 0

    notes = init_scaffold()
    print("Harbor-native OpenBench scaffold (.openbench/):")
    for note in notes:
        print(f"  {note}")
    print()
    print(
        "Next command (validate the default suite plan):\n"
        "  obench run --plan\n"
        "Then edit the suite, task, and profile for this repository.\n"
        "See docs/private-evals.md and docs/harbor-suites.md."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
